import type { Metadata } from 'next'
import { Sora, Poppins } from 'next/font/google'
import './globals.css'

const primary = Sora({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-primary',
})

const secondary = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-secondary',
})

export const metadata: Metadata = {
  title: 'Md. Mahdiul Hasan',
  description: "Md. Mahdiul Hasan's Portfolio Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${primary.variable} ${secondary.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        {children}
      </body>
    </html>
  )
}
