import { ThemeProvider } from '@/Provider/ThemeProvider'
import type { Metadata } from 'next'
import { Poppins, Sora } from 'next/font/google'
import './globals.css'

const fontPrimary = Sora({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-primary',
})

const fontSecondary = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-secondary',
})

export const metadata: Metadata = {
  title: 'Md. Mahdiul Hasan',
  description: "Md. Mahdiul Hasan's Portfolio Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <meta
        name="format-detection"
        content="telephone=no, date=no, email=no, address=no"
      />
      <body
        className={`${fontPrimary.variable} ${fontSecondary.variable} antialiased bg-background text-foreground`}
        cz-shortcut-listen="true"
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
